const SUPABASE_URL="https://qbbbpussyzkutonpvaze.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_QqqqICyurLbmaMBPUwfF_g_8_jVZYuO";
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
let user=null,records=[],month=new Date(),duty=9,signUp=false;
const $=id=>document.getElementById(id);
function fmt(n){return `${Number(n.toFixed(2))}h`}
function hours(inT,outT,breakMin=0){if(!inT||!outT)return 0;let [ih,im]=inT.split(':').map(Number),[oh,om]=outT.split(':').map(Number);let a=ih*60+im,b=oh*60+om;if(b<a)b+=1440;return Math.max(0,(b-a-breakMin)/60)}
function monthKey(){return `${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`}
async function init(){const {data:{session}}=await sb.auth.getSession();if(session){user=session.user;showApp();await load()}else showAuth();sb.auth.onAuthStateChange((_e,s)=>{if(s){user=s.user;showApp();load()}else showAuth()})}
function showAuth(){$('authView').classList.remove('hidden');$('appView').classList.add('hidden')}
function showApp(){$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('userEmail').textContent=user?.email||''}
$('toggleAuth').onclick=()=>{signUp=!signUp;$('authSubmit').textContent=signUp?'Create account':'Sign in';$('toggleAuth').textContent=signUp?'Already have an account? Sign in':'Create an account'}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='';let email=$('email').value,password=$('password').value;let r=signUp?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)$('authMessage').textContent=r.error.message;else if(signUp)$('authMessage').textContent='Account created. Check your email if confirmation is enabled.'}
$('logout').onclick=()=>sb.auth.signOut();
async function load(){let p=await sb.from('profiles').select('duty_hours').eq('id',user.id).single();if(p.data)duty=p.data.duty_hours||9;$('dutyHours').value=duty;let start=`${monthKey()}-01`,end=new Date(month.getFullYear(),month.getMonth()+1,0).toISOString().slice(0,10);let r=await sb.from('attendance').select('*').gte('work_date',start).lte('work_date',end).order('work_date',{ascending:false});records=r.data||[];render()}
function render(){let title=month.toLocaleString('en',{month:'long',year:'numeric'});$('monthTitle').textContent=title;let present=records.filter(x=>x.status==='present');let worked=present.reduce((s,x)=>s+hours(x.check_in,x.check_out,x.break_minutes),0),ot=present.reduce((s,x)=>s+Math.max(0,hours(x.check_in,x.check_out,x.break_minutes)-duty),0);$('workingDays').textContent=present.length;$('workedHours').textContent=fmt(worked);$('otHours').textContent=fmt(ot);$('regularHours').textContent=fmt(Math.max(0,worked-ot));renderCalendar();renderTable()}
function renderCalendar(){let c=$('calendar');c.innerHTML='';['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(x=>{let d=document.createElement('div');d.className='cal-head';d.textContent=x;c.appendChild(d)});let first=new Date(month.getFullYear(),month.getMonth(),1),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let i=0;i<first.getDay();i++){let d=document.createElement('div');d.className='day mutedday';c.appendChild(d)}for(let n=1;n<=days;n++){let date=`${monthKey()}-${String(n).padStart(2,'0')}`,r=records.find(x=>x.work_date===date),d=document.createElement('div');d.className='day';d.innerHTML=`<div class="daynum">${n}</div>`;if(r){let h=hours(r.check_in,r.check_out,r.break_minutes),ot=Math.max(0,h-duty);d.innerHTML+=`<span class="pill ${ot?'ot':r.status==='present'?'normal':'leave'}">${r.status==='present'?(ot?`+${fmt(ot)} OT`:fmt(h)):r.status}</span>`}d.onclick=()=>openDialog(r,date);c.appendChild(d)}}
function renderTable(){let t=$('records');t.innerHTML='';records.forEach(r=>{let h=hours(r.check_in,r.check_out,r.break_minutes),ot=Math.max(0,h-duty),tr=document.createElement('tr');tr.innerHTML=`<td>${r.work_date}</td><td>${r.check_in||'-'}</td><td>${r.check_out||'-'}</td><td>${r.break_minutes||0}m</td><td>${fmt(h)}</td><td><b>${fmt(ot)}</b></td><td class="status ${ot?'ot':r.status==='present'?'normal':'leave'}">${r.status}</td><td><button class="ghost edit">Edit</button></td>`;tr.querySelector('.edit').onclick=()=>openDialog(r);t.appendChild(tr)})}
function openDialog(r,date){$('attendanceDialog').showModal();$('recordId').value=r?.id||'';$('date').value=r?.work_date||date||new Date().toISOString().slice(0,10);$('checkIn').value=r?.check_in||'08:00';$('checkOut').value=r?.check_out||'17:00';$('breakMinutes').value=r?.break_minutes||0;$('status').value=r?.status||'present';$('notes').value=r?.notes||'';$('deleteRecord').classList.toggle('hidden',!r)}
$('attendanceForm').onsubmit=async e=>{e.preventDefault();let id=$('recordId').value,obj={user_id:user.id,work_date:$('date').value,check_in:$('checkIn').value,check_out:$('checkOut').value,break_minutes:Number($('breakMinutes').value||0),status:$('status').value,notes:$('notes').value};let r=id?await sb.from('attendance').update(obj).eq('id',id):await sb.from('attendance').insert(obj);if(r.error)alert(r.error.message);else{$('attendanceDialog').close();await load()}}
$('deleteRecord').onclick=async()=>{let id=$('recordId').value;if(id&&confirm('Delete this attendance record?')){await sb.from('attendance').delete().eq('id',id);$('attendanceDialog').close();load()}}
$('addToday').onclick=()=>openDialog(null,new Date().toISOString().slice(0,10));
$('prevMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);load()}
$('nextMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);load()}
$('saveSettings').onclick=async()=>{let v=Number($('dutyHours').value);if(v<=0||v>24)return alert('Enter duty hours between 0 and 24.');let r=await sb.from('profiles').upsert({id:user.id,duty_hours:v});if(r.error)alert(r.error.message);else{duty=v;render()}}
$('exportCsv').onclick=()=>{let rows=[['Date','Check In','Check Out','Break Minutes','Worked Hours','Overtime Hours','Status','Notes'],...records.map(r=>{let h=hours(r.check_in,r.check_out,r.break_minutes),ot=Math.max(0,h-duty);return[r.work_date,r.check_in,r.check_out,r.break_minutes,h.toFixed(2),ot.toFixed(2),r.status,r.notes||'']})];let csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`worktrack-${monthKey()}.csv`;a.click()}
init();
